#!/bin/bash

: ${1?"Usage: $0 <language>"}

set -e

export NODE_LANG=$1
export NODE_ENV=development
export ASSET_VERSIONING=query
export WATCH=1
export SITE_HOST=http://javascript.local
export PORT=3000

npm --silent run gulp dev | bunyan -o short -l debug

