#!/bin/bash

: ${1?"Usage: $0 <language>"}

BRANCH="${1:-$NODE_LANG}"

export NODE_LANG=$BRANCH
export NODE_ENV=production
export TUTORIAL_EDIT=1
export PLUNK_REMOTE_OFF=1

npm --silent run -- gulp tutorial:import --root /js/javascript-tutorial-$BRANCH
npm --silent run -- gulp edit --root /js/javascript-tutorial-$BRANCH

